version: "3.3"
services:
  crypto-notify:
    image: oat9002/crypto-notify:latest
    ports:
      - 8081:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthCheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
