name: docker

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        description: 'docker username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'docker token'
        required: true

jobs:
  dockerPublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current app version
        id: get-app-version
        run: |
          export VERSION=$(cat version.sbt | cut -d '"' -f2 | sed 's/-SNAPSHOT//g')
          echo "version: $VERSION"
          echo "::set-output name=APP_VERSION::$VERSION"
      - name: Create Dockerfile
        run: sbt "Docker / stage"
      - name: Publish to Docker Hub
        run: |
          cd ./target/docker/stage
          docker buildx build --platform="linux/amd64,linux/arm64,linux/arm/v7" -t oat9002/crypto-notify:latest -t oat9002/crypto-notify:${{ steps.get-app-version.outputs.APP_VERSION }} --push .