name: docker

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        description: 'docker username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'docker token'
        required: true

jobs:
  dockerPublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create Dockerfile
        run: sbt "Docker / stage"
      - name: Go to Dockerfile dir
        run: |
          - cd ./target/docker/stage
          - pwd
      - name: Get current app version
        id: get-app-version
        run: |
          - echo '::set-output name=APP_VERSION::$(sbt 'show version' | tail -n1 | cut -d " " -f2)'
      - name: Publish to Docker Hub
        run: docker buildx build --platform="linux/amd64,linux/arm64,linux/arm/v7" -t oat9002/crypto-notify:latest -t oat9002/crypto-notify:${{ steps.get-app-version.outputs.APP_VERSION }} --push .

