name: manual-update-version

on: workflow_dispatch

jobs:
  updateVersion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.PUSH_TOKEN }}
          ref: main
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Set GitHub user
        run: |
          git config --global user.name 'oat9002'
          git config --global user.email 'oat9002@hotmail.com'
      - name: Release
        run: sbt "release with-defaults"
        env: 
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
