name: pr_build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'github-actions[bot]' }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        persist-credentials: false
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Set Git Username
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Format code
      run: |
        sbt scalafmtAll
    - name: Clean and Compile
      run: sbt clean compile
    - name: Check for changes
      run: |
        if git diff-index --quiet HEAD; then
          echo "IS_CHANGED=false" >> $GITHUB_ENV
        else
          echo "IS_CHANGED=true" >> $GITHUB_ENV
        fi
    - name: Push code if format is needed
      if: ${{ env.IS_CHANGED == 'true' }}
      run: |
        git add --all
        git commit -m ":recycle: format code"
        git push origin ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: build
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Test
      run: sbt test

