name: pr_build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Set Git Username
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Format code
      run: | 
        sbt scalafmtAll
        git add --all
        git diff-index --quiet HEAD || (git commit -m ":recycle: format code" | git status | git push origin ${{ github.head_ref }})
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Clean and Compile
      run: sbt clean compile

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Test
      run: sbt test

