name: release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Set GitHub user
        run: |
          git config --global user.name 'oat9002'
          git config --global user.email 'oat9002@hotmail.com'
      - name: Release
        run: sbt "release with-defaults"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  githubRelease:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set GitHub user
        run: |
          git config --global user.name 'oat9002'
          git config --global user.email 'oat9002@hotmail.com'
      - name: Get latest tag
        run: |
          git pull
          echo ::set-output name=LATEST_TAG::$(git describe --tags --abbrev=0)
        id: get-latest-tag
      - name: Checkout to latest tag
        run: git checkout tags/${{ steps.get-latest-tag.outputs.LATEST_TAG }}
      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get-latest-tag.outputs.LATEST_TAG }}

  deploy:
    needs: release
    uses: oat9002/crypto-notify/.github/workflows/deploy.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SERVER_URL: ${{ secrets.SERVER_URL }}
      DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}


